<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Beneficiaire;
use App\Enums\Type;
use App\Enums\Zone;
use App\Enums\Sexe;
use App\Enums\Genre;

class BeneficiaireSeeder extends Seeder
{
    public function run(): void
    {

        $data = [
[
                'ben_prenom' => 'william',
                'ben_nom' => 'riley',
                'ben_date_naissance' => '1983-01-08',
                'ben_region' => 'Africa',
                'ben_pays' => 'Senegal',
                'ben_type' => Type::TRAVAILLEUR_SOCIAL,
                'ben_type_autre' => null,
                'ben_zone' => Zone::URBAINE,
                'ben_sexe' => Sexe::FEMME,
                'ben_sexe_autre' => null,
                'ben_genre' => Genre::HOMO,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'mixed',
            ],

[
                'ben_prenom' => 'victoria',
                'ben_nom' => 'hart',
                'ben_date_naissance' => '1985-07-13',
                'ben_region' => 'Africa',
                'ben_pays' => 'Ivory Coast',
                'ben_type' => Type::ENFANT,
                'ben_type_autre' => null,
                'ben_zone' => Zone::RURALE,
                'ben_sexe' => Sexe::AUTRE,
                'ben_sexe_autre' => 'until',
                'ben_genre' => Genre::NON_BINAIRE,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'native',
            ],

[
                'ben_prenom' => 'megan',
                'ben_nom' => 'garcia',
                'ben_date_naissance' => '2000-05-09',
                'ben_region' => 'Africa',
                'ben_pays' => 'Cameroon',
                'ben_type' => Type::AUTRE,
                'ben_type_autre' => 'reduce',
                'ben_zone' => Zone::PERIURBAINE,
                'ben_sexe' => Sexe::AUTRE,
                'ben_sexe_autre' => 'throw',
                'ben_genre' => Genre::HOMO,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'latino',
            ],

[
                'ben_prenom' => 'steven',
                'ben_nom' => 'oconnor',
                'ben_date_naissance' => '1968-05-26',
                'ben_region' => 'Africa',
                'ben_pays' => 'Morocco',
                'ben_type' => Type::JEUNE,
                'ben_type_autre' => null,
                'ben_zone' => Zone::URBAINE,
                'ben_sexe' => Sexe::HOMME,
                'ben_sexe_autre' => null,
                'ben_genre' => Genre::NON_BINAIRE,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'european',
            ],

[
                'ben_prenom' => 'katrina',
                'ben_nom' => 'fields',
                'ben_date_naissance' => '1970-06-19',
                'ben_region' => 'Africa',
                'ben_pays' => 'Nigeria',
                'ben_type' => Type::PSYCHOLOGUE,
                'ben_type_autre' => null,
                'ben_zone' => Zone::URBAINE,
                'ben_sexe' => Sexe::HOMME,
                'ben_sexe_autre' => null,
                'ben_genre' => Genre::HOMO,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'asian',
            ],

[
                'ben_prenom' => 'ivan',
                'ben_nom' => 'williams',
                'ben_date_naissance' => '1982-05-22',
                'ben_region' => 'Europe',
                'ben_pays' => 'France',
                'ben_type' => Type::JEUNE,
                'ben_type_autre' => null,
                'ben_zone' => Zone::URBAINE,
                'ben_sexe' => Sexe::AUTRE,
                'ben_sexe_autre' => 'face',
                'ben_genre' => Genre::HOMO,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'latino',
            ],

[
                'ben_prenom' => 'david',
                'ben_nom' => 'delacruz',
                'ben_date_naissance' => '1995-10-01',
                'ben_region' => 'Europe',
                'ben_pays' => 'Germany',
                'ben_type' => Type::PARENT,
                'ben_type_autre' => null,
                'ben_zone' => Zone::RURALE,
                'ben_sexe' => Sexe::FEMME,
                'ben_sexe_autre' => null,
                'ben_genre' => Genre::CIS_HETERO,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'european',
            ],

[
                'ben_prenom' => 'nicole',
                'ben_nom' => 'martin',
                'ben_date_naissance' => '1994-01-01',
                'ben_region' => 'Europe',
                'ben_pays' => 'Italy',
                'ben_type' => Type::PARTENAIRE,
                'ben_type_autre' => null,
                'ben_zone' => Zone::URBAINE,
                'ben_sexe' => Sexe::FEMME,
                'ben_sexe_autre' => null,
                'ben_genre' => Genre::CIS_HETERO,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'native',
            ],

[
                'ben_prenom' => 'samuel',
                'ben_nom' => 'hammond',
                'ben_date_naissance' => '2004-11-22',
                'ben_region' => 'Europe',
                'ben_pays' => 'Spain',
                'ben_type' => Type::PARTENAIRE,
                'ben_type_autre' => null,
                'ben_zone' => Zone::RURALE,
                'ben_sexe' => Sexe::AUTRE,
                'ben_sexe_autre' => 'modern',
                'ben_genre' => Genre::CIS_HETERO,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'latino',
            ],

[
                'ben_prenom' => 'harry',
                'ben_nom' => 'werner',
                'ben_date_naissance' => '2003-03-04',
                'ben_region' => 'Europe',
                'ben_pays' => 'Switzerland',
                'ben_type' => Type::AUTORITE_LOCALE,
                'ben_type_autre' => null,
                'ben_zone' => Zone::PERIURBAINE,
                'ben_sexe' => Sexe::FEMME,
                'ben_sexe_autre' => null,
                'ben_genre' => Genre::AUTRE,
                'ben_genre_autre' => 'authority',
                'ben_ethnicite' => 'european',
            ],

[
                'ben_prenom' => 'sara',
                'ben_nom' => 'frey',
                'ben_date_naissance' => '1989-04-07',
                'ben_region' => 'Asia',
                'ben_pays' => 'India',
                'ben_type' => Type::PSYCHOLOGUE,
                'ben_type_autre' => null,
                'ben_zone' => Zone::PERIURBAINE,
                'ben_sexe' => Sexe::AUTRE,
                'ben_sexe_autre' => 'head',
                'ben_genre' => Genre::AUTRE,
                'ben_genre_autre' => 'production',
                'ben_ethnicite' => 'asian',
            ],

[
                'ben_prenom' => 'jeffrey',
                'ben_nom' => 'hernandez',
                'ben_date_naissance' => '1988-11-21',
                'ben_region' => 'Asia',
                'ben_pays' => 'China',
                'ben_type' => Type::JEUNE,
                'ben_type_autre' => null,
                'ben_zone' => Zone::PERIURBAINE,
                'ben_sexe' => Sexe::FEMME,
                'ben_sexe_autre' => null,
                'ben_genre' => Genre::AUTRE,
                'ben_genre_autre' => 'want',
                'ben_ethnicite' => 'mixed',
            ],

[
                'ben_prenom' => 'isabella',
                'ben_nom' => 'ford',
                'ben_date_naissance' => '2000-02-08',
                'ben_region' => 'Asia',
                'ben_pays' => 'Japan',
                'ben_type' => Type::PARENT,
                'ben_type_autre' => null,
                'ben_zone' => Zone::PERIURBAINE,
                'ben_sexe' => Sexe::AUTRE,
                'ben_sexe_autre' => 'spend',
                'ben_genre' => Genre::FLUIDE,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'european',
            ],

[
                'ben_prenom' => 'michael',
                'ben_nom' => 'santiago',
                'ben_date_naissance' => '1993-09-11',
                'ben_region' => 'Asia',
                'ben_pays' => 'Indonesia',
                'ben_type' => Type::AUTORITE_LOCALE,
                'ben_type_autre' => null,
                'ben_zone' => Zone::URBAINE,
                'ben_sexe' => Sexe::HOMME,
                'ben_sexe_autre' => null,
                'ben_genre' => Genre::CIS_HETERO,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'asian',
            ],

[
                'ben_prenom' => 'jasmin',
                'ben_nom' => 'peterson',
                'ben_date_naissance' => '2003-08-23',
                'ben_region' => 'Asia',
                'ben_pays' => 'Philippines',
                'ben_type' => Type::TRAVAILLEUR_SOCIAL,
                'ben_type_autre' => null,
                'ben_zone' => Zone::URBAINE,
                'ben_sexe' => Sexe::HOMME,
                'ben_sexe_autre' => null,
                'ben_genre' => Genre::BI,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'arab',
            ],

[
                'ben_prenom' => 'diana',
                'ben_nom' => 'koch',
                'ben_date_naissance' => '1997-06-15',
                'ben_region' => 'Americas',
                'ben_pays' => 'Brazil',
                'ben_type' => Type::AUTRE,
                'ben_type_autre' => 'arrive',
                'ben_zone' => Zone::RURALE,
                'ben_sexe' => Sexe::HOMME,
                'ben_sexe_autre' => null,
                'ben_genre' => Genre::AUTRE,
                'ben_genre_autre' => 'rate',
                'ben_ethnicite' => 'african',
            ],

[
                'ben_prenom' => 'carol',
                'ben_nom' => 'henry',
                'ben_date_naissance' => '1999-07-22',
                'ben_region' => 'Americas',
                'ben_pays' => 'Brazil',
                'ben_type' => Type::PSYCHOLOGUE,
                'ben_type_autre' => null,
                'ben_zone' => Zone::URBAINE,
                'ben_sexe' => Sexe::FEMME,
                'ben_sexe_autre' => null,
                'ben_genre' => Genre::BI,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'arab',
            ],

[
                'ben_prenom' => 'allison',
                'ben_nom' => 'thompson',
                'ben_date_naissance' => '1965-04-11',
                'ben_region' => 'Americas',
                'ben_pays' => 'Brazil',
                'ben_type' => Type::ENSEIGNANT,
                'ben_type_autre' => null,
                'ben_zone' => Zone::PERIURBAINE,
                'ben_sexe' => Sexe::FEMME,
                'ben_sexe_autre' => null,
                'ben_genre' => Genre::CIS_HETERO,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'mixed',
            ],

[
                'ben_prenom' => 'gabriel',
                'ben_nom' => 'sullivan',
                'ben_date_naissance' => '1974-12-01',
                'ben_region' => 'Americas',
                'ben_pays' => 'Mexico',
                'ben_type' => Type::PSYCHOLOGUE,
                'ben_type_autre' => null,
                'ben_zone' => Zone::URBAINE,
                'ben_sexe' => Sexe::AUTRE,
                'ben_sexe_autre' => 'seat',
                'ben_genre' => Genre::HOMO,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'mixed',
            ],

[
                'ben_prenom' => 'christina',
                'ben_nom' => 'terrell',
                'ben_date_naissance' => '1975-04-15',
                'ben_region' => 'Americas',
                'ben_pays' => 'Argentina',
                'ben_type' => Type::AUTORITE_LOCALE,
                'ben_type_autre' => null,
                'ben_zone' => Zone::URBAINE,
                'ben_sexe' => Sexe::AUTRE,
                'ben_sexe_autre' => 'south',
                'ben_genre' => Genre::FLUIDE,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'native',
            ],

[
                'ben_prenom' => 'jenny',
                'ben_nom' => 'smith',
                'ben_date_naissance' => '1973-01-22',
                'ben_region' => 'Oceania',
                'ben_pays' => 'Australia',
                'ben_type' => Type::PARENT,
                'ben_type_autre' => null,
                'ben_zone' => Zone::PERIURBAINE,
                'ben_sexe' => Sexe::AUTRE,
                'ben_sexe_autre' => 'without',
                'ben_genre' => Genre::BI,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'mixed',
            ],

[
                'ben_prenom' => 'stephen',
                'ben_nom' => 'miller',
                'ben_date_naissance' => '1983-04-01',
                'ben_region' => 'Oceania',
                'ben_pays' => 'New Zealand',
                'ben_type' => Type::AUTRE,
                'ben_type_autre' => 'finish',
                'ben_zone' => Zone::PERIURBAINE,
                'ben_sexe' => Sexe::FEMME,
                'ben_sexe_autre' => null,
                'ben_genre' => Genre::CIS_HETERO,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'native',
            ],

[
                'ben_prenom' => 'sean',
                'ben_nom' => 'rivera',
                'ben_date_naissance' => '1982-07-31',
                'ben_region' => 'Oceania',
                'ben_pays' => 'Fiji',
                'ben_type' => Type::ENSEIGNANT,
                'ben_type_autre' => null,
                'ben_zone' => Zone::URBAINE,
                'ben_sexe' => Sexe::HOMME,
                'ben_sexe_autre' => null,
                'ben_genre' => Genre::HOMO,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'native',
            ],

[
                'ben_prenom' => 'kevin',
                'ben_nom' => 'sanders',
                'ben_date_naissance' => '1975-01-27',
                'ben_region' => 'Oceania',
                'ben_pays' => 'Samoa',
                'ben_type' => Type::PSYCHOLOGUE,
                'ben_type_autre' => null,
                'ben_zone' => Zone::URBAINE,
                'ben_sexe' => Sexe::FEMME,
                'ben_sexe_autre' => null,
                'ben_genre' => Genre::NON_BINAIRE,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'arab',
            ],

[
                'ben_prenom' => 'daniel',
                'ben_nom' => 'benton',
                'ben_date_naissance' => '2006-01-19',
                'ben_region' => 'Oceania',
                'ben_pays' => 'Papua New Guinea',
                'ben_type' => Type::ENFANT,
                'ben_type_autre' => null,
                'ben_zone' => Zone::URBAINE,
                'ben_sexe' => Sexe::AUTRE,
                'ben_sexe_autre' => 'notice',
                'ben_genre' => Genre::BI,
                'ben_genre_autre' => null,
                'ben_ethnicite' => 'arab',
            ],
        ];

        foreach ($data as $item) {
            Beneficiaire::create($item);
        }
    }
}